### ISSUE TITLE
Connecting to the databse: password authentication failed

### ISSUE THREAD

**Issue by ratnanil** [rsangole/postgres#1]
I landed here through your [excellent blogpost](https://rsangole.netlify.app/post/2021/08/07/docker-based-rstudio-postgres/) on the subject. I successfully followed the [first time setup](https://rsangole.netlify.app/post/2021/08/07/docker-based-rstudio-postgres/#first-time-setup) and was also able to run `docker-compose up -d; firefox localhost:8787`. However, connecting to the databse failed (using [postgres.R](https://github.com/rsangole/postgres/blob/master/postgres.R)), I get following error message: 

    Error: FATAL:  password authentication failed for user "rahul"

I purposefully did not change any of your settings, the error is not due to a typo... Any clue why this is happening?

**Comment by ratnanil** [comment]
I'm not sure what I did wrong, but somehow I didn't create the user `rahul`. Redoing this step solved the issue

**Comment by rsangole** [comment]
Great, glad you figured it out! You could be my first external user (tester?). Let me know if you face any issues!

**Comment by ratnanil** [comment]
Its quite an amazing blogpost, I'm quite amazed. Since I've got you "on the line", a quick question: What if I want to access the data stored in the database from outside the container, i.e. my local ubuntu installation. How would i need to go about doing that? The way I understand it, the data is stored in a mounted device, not in the container, right?

**Comment by rsangole** [comment]
That's correct. The data is stored on your local disk and only mounted within the container. So you can directly access it just like you normally would - using pgadmin or vscode etc, or even other docker containers simultaneously.
